# Generated by Django 6.0rc1 on 2026-01-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
